# Generated by Django 3.1.1 on 2020-11-05 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
    ]
